twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        # the value is the service's id 
        pollutingRepository: '@App\Repository\PollutingRepository'
        productRepository: '@App\Repository\ProductRepository'
        roomsRepository: '@App\Repository\RoomsRepository' 
when@test:
    twig:
        strict_variables: true
